# Generated by Django 3.1.3 on 2021-02-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0005_auto_20210227_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='in_progress',
        ),
    ]
