# Generated by Django 3.1.3 on 2021-02-01 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='issue',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 1, 13, 20, 466106, tzinfo=utc), verbose_name='date_posted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('C', 'Critical'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=1),
        ),
    ]
