# Generated by Django 3.1.3 on 2021-02-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0005_auto_20210227_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_completed',
            field=models.DateTimeField(null=True, verbose_name='date_completed'),
        ),
    ]
