# Generated by Django 3.1.3 on 2021-02-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0006_auto_20210227_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='date_completed',
            field=models.DateTimeField(null=True, verbose_name='date_completed'),
        ),
        migrations.AddField(
            model_name='issue',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
