# Generated by Django 3.1.3 on 2021-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0008_issue_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_posted',
            field=models.DateTimeField(null=True, verbose_name='date_posted'),
        ),
    ]
