# Generated by Django 3.1.3 on 2021-07-03 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0009_auto_20210701_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_posted'),
            preserve_default=False,
        ),
    ]
