# Generated by Django 3.1.3 on 2021-07-03 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0011_auto_20210702_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='date_posted',
        ),
    ]
